<h2>Debre Berhan University  
Computing College 
Computer Science Department </h2>
<h3>Machine Learning (CoSc3114) Lab Worksheet-3  
Exercise on Data Preprocessing  </h3>

8. Transform the dataset to Min-Max Normalization 

In [1]:
#8.	Transform the dataset to Min-Max Normalization
import math as m
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
file_path = r"C:\Users\yifru\OneDrive\Desktop\machine learning\worksheet three\iris\iris.data"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
data=pd.read_csv(file_path, names=names)
data2= (data.iloc[:,:-1])
print (data2.head())
print (data2.shape)
Scaler=MinMaxScaler()
ScaledData=Scaler.fit_transform (data2)
ScaledData=ScaledData.round(2)
print (ScaledData)
print (ScaledData.shape)

   sepal-length  sepal-width  petal-length  petal-width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2
(150, 4)
[[0.22 0.62 0.07 0.04]
 [0.17 0.42 0.07 0.04]
 [0.11 0.5  0.05 0.04]
 [0.08 0.46 0.08 0.04]
 [0.19 0.67 0.07 0.04]
 [0.31 0.79 0.12 0.12]
 [0.08 0.58 0.07 0.08]
 [0.19 0.58 0.08 0.04]
 [0.03 0.38 0.07 0.04]
 [0.17 0.46 0.08 0.  ]
 [0.31 0.71 0.08 0.04]
 [0.14 0.58 0.1  0.04]
 [0.14 0.42 0.07 0.  ]
 [0.   0.42 0.02 0.  ]
 [0.42 0.83 0.03 0.04]
 [0.39 1.   0.08 0.12]
 [0.31 0.79 0.05 0.12]
 [0.22 0.62 0.07 0.08]
 [0.39 0.75 0.12 0.08]
 [0.22 0.75 0.08 0.08]
 [0.31 0.58 0.12 0.04]
 [0.22 0.71 0.08 0.12]
 [0.08 0.67 0.   0.04]
 [0.22 0.54 0.12 0.17]
 [0.14 0.58 0.15 0.04]
 [0.19 0.42 0.1  0.04]
 [0.19 0.58 0.1  0.12]
 [0.25 0.62 0.08 0.04]
 [0.25 0.58